# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'

target 'Hawkeye Example App' do
  
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Hawkeye Example App
  pod 'Hawkeye', :git => 'https://github.com/matthewmoss/hawkeye-ios-sdk'

end
